### PR TITLE
RFC for Project Descriptor Flexibility

### PR DESCRIPTION
**Pull request by hone**
[readable](https://github.com/buildpacks/rfcs/blob/project-descriptor-flexibility/text/0000-project-descriptor-flexibility.md)

### CODE REVIEW

**Comment by nebhale** [comment]
@hone What is the compatibility store for the future if the CNB project does want to reserve a new top-level key beyond `[<filename>]` and `[build]`?  What's the story for preventing collisions in the top-level namespace between different platforms and projects?

**Comment by jkutner** [comment]
@nebhale in working group we discussed moving `[build]` (and any keys we need to define) under the top-level table, yielding:

```
[project]
id = ....

[[project.build.buildpacks]]
id = ...
```

We'd then commit to not using anything outside of the project/top-level table

**Comment by nebhale** [comment]
@jkutner I'm not sure that we can make that commitment though.  And if we did, it could significantly constrain new features we might want to introduce, that we haven't thought of before.  This is why putting user configuration into a single key that we _can_ keep our hands off of, is so compelling.  It gives us a story where we can add new features without conflict with user configuration.

**Comment by jkutner** [comment]
@nebhale on the flip side: platforms won't use the `[metadata]` table if they don't adopt the file format. I think we are more likely to see `project.toml` adoption if we force ourselves under one key, rather than forcing our adopters under one key.

**Comment by dfreilich** [comment]
Is there a request for this? Have other projects expressed interest in also using `project.toml`, such that we're focusing on making it compatible for that?

**Comment by dfreilich** [comment]
Also, I'm a bit confused by what you describe the current behavior is. Is that to say that if the descriptor is `app.toml`, it will expect an `[app]` key, and if the descriptor is `build.toml`, it will expect a `[build]` key?

**Comment by jkutner** [comment]
@dfreilich yes, that's what I'm proposing

**Comment by hone** [comment]
> Is there a request for this? Have other projects expressed interest in also using `project.toml`, such that we're focusing on making it compatible for that?

This came out of a request internally at Salesforce/Heroku where the issue with the current `project.toml` requiring Salesforce specific config being forced under `[metadata]` made it feel like a second class citizen for a config for specific to the platform.

**Comment by briandealwis** [comment]
And if I call it `build.toml` then we… have a conflct?

Would it make sense to allow providing a "configurator" that could synthesize a CNB project descriptor from the workspace?  That could be useful for downstream projects that already use a different format than toml.

**Comment by hone** [comment]
Based on feedback from the group #140 supersedes this RFC, so I'm going to close this.

**Pull request closed without merging**
