### PR TITLE
CVE Backporting rfc

### PR DESCRIPTION
**Pull request by joe-kimmel-vmw**

### CODE REVIEW

**Comment by natalieparellano** [comment]
Marking this as ready-for-review

**Review by samj1912 — APPROVED** [review]

**Comment by natalieparellano** [comment]
Moving to status/voting with close date of next Friday, March 31

**Review by natalieparellano — APPROVED** [review]

**Review by hone — COMMENTED** [review]
Will we be documenting this policy somewhere?

**Review by hone — APPROVED** [review]

**Comment by natalieparellano** [comment]
> Will we be documenting this policy somewhere?

It might make sense to add notes to https://github.com/buildpacks/lifecycle/blob/main/RELEASE.md. But maybe there's a better place to put it...

**Comment by samj1912** [comment]
Potentially https://github.com/buildpacks/community/blob/main/VERSIONING.md or our SECURITY.md?

**Pull request merged**
